# Uncomment the next line to define a global platform for your project
platform :ios, '10.0' 

#忽略引入库的警告
inhibit_all_warnings!

def common
    #WeexSDK
    #pod 'WeexSDK', :git => 'https://github.com/bmfe/incubator-weex.git'
    pod 'WeexSDK', :git => 'https://gitlab.sjfood.us/Eddy.M/incubator-weex.git'

    #Weex debugger 调试工具，只在开发模式集成
    #pod 'WXDevtool', :git => 'https://github.com/bmfe/weex-devtool-iOS.git', :configurations => ['Debug']
    pod 'WXDevtool', :git => 'https://gitlab.sjfood.us/Eddy.M/weex-devtool-iOS.git', :configurations => ['Debug']

    #Eros iOS 基础库 1.3.5
    #pod 'ErosPluginBaseLibrary', :git => 'https://github.com/bmfe/eros-plugin-ios-baseLibrary.git', :tag => '1.3.6'
    #pod 'ErosPluginBaseLibrary', :git => 'https://github.com/mayuanyang/eros-plugin-ios-baseLibrary.git'
    pod 'ErosPluginBaseLibrary', :git => 'https://gitlab.sjfood.us/Eddy.M/eros-plugin-ios-baseLibrary.git'
    
    # 友盟+ 基础依赖库
    pod 'UMCCommon'
    # 安全组件 可选
    #pod 'UMCSecurityPlugins'
    
    # 1 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    
    # 2.集成Facebook/Messenger
    pod 'UMCShare/Social/Facebook'
   
    # 3.集成Google+
    pod 'UMCShare/Social/GooglePlus'
    
    # 4.集成Twitter
    pod 'UMCShare/Social/Twitter'
    
    # 5.google+登陆(导入不成功,手动导入)
    #pod 'GoogleSignIns'
    
    # 6.Microsoft 微软登陆
    pod 'MSAL'
    
end

target 'ErosPluginSocialShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ErosPluginSocialShare

  common

  target 'ErosPluginSocialShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ErosPluginSocialShareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
